services:

#none of those ports are set up correctly, i dont care
#       same for some of the paths (still don't care)

#backend-server
  django:
    image: django
    container_name: django
    networks:
      - tr-speedrun-network
    expose:
      - "8000"
    build:
      context: /home/ubuntu/transcendance/backend/django
      dockerfile: Dockerfile
    env_file: .env
    #depends_on:
    #  - wordpress
    volumes:
      - django:/var/backend/backend_server
    #restart: unless-stopped

#backend-db  
  postgre:
    image: postgre
    container_name: postgre
    expose:
      - "5432"
    networks:
      - tr-speedrun-network
    build:
      context: /home/ubuntu/transcendance/backend/db
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - postgre:/var/backend/backend_db
    restart: on-failure

#WAF security middleware
  middleware:
    image: middleware
    container_name: middleware
    ports:
      - "8443:8443"
    networks:
      - tr-speedrun-network
    build:
      context: /home/ubuntu/transcendance/middleware/
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - django
    volumes:
      - middleware:/var/backend/waf
    #restart: on-failure

#front (only for building npm then is turned off)
#       may or may not need ports (don't know don't care)
    frontend:
      image: frontend
      container_name: frontend
      ports:
        - "8080:8080"
      networks:
        - tr-speedrun-network
      build:
        context: /home/ubuntu/transcendance/frontend/
        dockerfile: Dockerfile
      volumes:
       - frontend:/usr/src/app/

volumes:
  django:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/ubuntu/data/backend_django'
  postgre:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/ubuntu/data/backend_db'
  middleware:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/ubuntu/data/waf_rules'

networks:
  tr-speedrun-network:
    driver: bridge
