services:

#none of those ports are set up correctly, i dont care
#       same for some of the paths (still don't care)

#backend-server
  django:
    image: django
    container_name: django
    networks:
      - tr-speedrun-network
    expose:
      - "8000"
    build:
      context: /home/ubuntu/transcendance/backend/django
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - postgre
      - vault
    volumes:
      - django:/var/www/django/static/
      - django:/var/www/django/media/
      - postgre:/var/lib/postgresql/data/
      - vault:/etc/vault
    restart: on-failure

#backend-db  
  postgre:
    image: postgre
    container_name: postgre
    expose:
      - "5432"
    networks:
      - tr-speedrun-network
    build:
      context: /home/ubuntu/transcendance/backend/db
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - postgre:/var/lib/postgresql/data/
    restart: on-failure

#backend-vault (hashicorp)
  vault:
    image: vault
    container_name: vault
    expose:
      - "8200"
    networks:
      - tr-speedrun-network
    build:
      context: /home/ubuntu/transcendance/backend/vault
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - vault:/etc/vault.d/
    restart: unless-stopped


#WAF security middleware
  middleware:
    image: middleware
    container_name: middleware
    ports:
      - "8443:8443"
    networks:
      - tr-speedrun-network
    build:
      context: /home/ubuntu/transcendance/middleware/
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - django
    volumes:
      - middleware:/etc/conf/
      - middleware:/var/log/
    restart: unless-stopped

#front (only for building npm then is turned off)
#       may or may not need ports (don't know don't care)
    frontend:
      image: frontend
      container_name: frontend
      ports:
        - "8080:8080"
      networks:
        - tr-speedrun-network
      build:
        context: /home/ubuntu/transcendance/frontend/
        dockerfile: Dockerfile
      depends_on:
        - django
        - middleware
        - postgre
        - vault
      restart: on-failure

volumes:
  - django:
  - postgre:
  - vault:
  - middleware:

networks:
  tr-speedrun-network:
    driver: bridge
